cam = view_camera[0];
follow = oPlayer;
w = camera_get_view_width(cam);
h = camera_get_view_height(cam);
view_w_half = w/2;
view_h_half = h/2;
xToFollow = xstart;
yToFollow = ystart;
buff = 32;
strength = 25; // less strength means stronger